version: 0.1

phases:
  pre_build:
    commands:
      - echo "pre build"
      - chmod -R +x *.sh
      - cd website
      - npm install
      - cd ..
  build:
    commands:
      - echo "build"
      - cd website
      - npm run build
      - cd ..
  post_build:
    commands:
      - echo "post build"
      - ./publish.sh
